### ISSUE TITLE
app crash when change view by in report section

### ISSUE THREAD

**Issue by muhammadarif1** [zwieback/FamilyFinance#1]
#### EXPECTED BEHAVIOR
when the user changes the appearance of the report from "view value" to "use percent value" this application will still work properly and will display report data in accordance with the wishes of the user
#### ACTUAL BEHAVIOR
when the user changes the appearance of the report from "view value" to "use percent value" this application will crash and stop working
#### STEPS TO REPRODUCE
- install and open the app
- click "report" option
- scroll to the right side to "incomes by articles or expenses by articles
- click eye icon
- change view by "view values" to "use percent values" 
- see errors
**devices**
- phone models: oppo neo 7
- os                  : android 6.1
#### BUG RECORDING
https://www.youtube.com/watch?v=MYMrVP3fQ_g&feature=youtu.be
logcat
```FATAL EXCEPTION: main
Process: io.github.zwieback.familyfinance, PID: 13191
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.github.mikephil.charting.data.PieData.setDrawValues(boolean)' on a null object reference
	at io.github.zwieback.familyfinance.business.chart.fragment.PieChartFragment.onApplyDisplay(PieChartFragment.java:160)
	at io.github.zwieback.familyfinance.business.chart.fragment.PieChartFragment.onApplyDisplay(PieChartFragment.java:40)
	at io.github.zwieback.familyfinance.business.chart.activity.ChartActivity.onApplyDisplay(ChartActivity.java:150)
	at io.github.zwieback.familyfinance.business.chart.dialog.ChartDisplayDialog.lambda$onCreateDialog$0(ChartDisplayDialog.java:53)
	at io.github.zwieback.familyfinance.business.chart.dialog.-$$Lambda$ChartDisplayDialog$3JuCWsAV3m9zaJu55iVYBsSndyU.onClick(lambda)
	at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by muhammadarif1** [comment]
Please givea feefback sir

**Comment by zwieback** [comment]
Good day!

Thank you for a such detailed description of crash reasons.

I have already fixed this issue according to the description provided. The fix will be released in the next release.

**Comment by zwieback** [comment]
Fixed in [this commit](https://github.com/zwieback/FamilyFinance/commit/4d1e8446b45d0e425d321255ccf61ec028d6ebd6).
